import S, { BaseSchema } from 'jsonschema-definer'
import Loki, { Collection } from 'lokijs'
import XRegExp from 'xregexp'

import { sDictType, sLevel } from '@/util/schema'

export let zh: Loki

export const sDict = S.shape({
  entry: S.string(), // Unique if exists / possible
  alt: S.list(S.string()).minItems(1).uniqueItems().optional(),
  reading: S.list(S.string()).minItems(1).uniqueItems(), // Autogenerated, if possible
  english: S.list(S.string()).minItems(1).uniqueItems(),
  frequency: S.number().optional(), // sortable
  level: sLevel.optional(),
})

export let zhDict: Record<typeof sDictType.type, Collection<typeof sDict.type>>

const reHan1 = XRegExp('^\\p{Han}$')
const sHan1 = S.string().custom((s) => reHan1.test(s))

export const sToken = S.shape({
  entry: sHan1,
  sub: S.list(sHan1).minItems(1).uniqueItems().optional(),
  sup: S.list(sHan1).minItems(1).uniqueItems().optional(),
  variants: S.list(sHan1).minItems(1).uniqueItems().optional(),
  frequency: S.number().optional(), // sortable
})

export let zhToken: Collection<typeof sToken.type>

export async function zhInit(filename = 'assets/zh.loki') {
  return new Promise((resolve) => {
    zh = new Loki(filename, {
      autoload: true,
      autoloadCallback: async () => {
        const getCollection = (name: typeof sDictType.type) => {
          let col: Collection<typeof sDict.type> = zh.getCollection(name)
          if (!col) {
            col = zh.addCollection(name, {
              unique: ['entry'],
              indices: ['alt', 'frequency', 'level'],
            })
          }
          return col
        }

        zhDict = {
          hanzi: getCollection('hanzi'),
          vocab: getCollection('vocab'),
          sentence: getCollection('sentence'),
        }

        zhToken = zh.getCollection('token')
        if (!zhToken) {
          zhToken = zh.addCollection('token', {
            unique: ['entry'],
            indices: ['variants', 'frequency'],
          })
        }

        resolve()
      },
    })
  })
}

export function ensureSchema<T extends BaseSchema>(
  schema: T,
  data: T['type']
): T['type'] {
  const [, err] = schema.validate(data)
  if (err) {
    throw new Error((err[0] || {}).message)
  }

  return data as any
}
